version: 3.9
container-name: bankly-masstransit-basics
services:
  rabbit-mq:
    image: "bitnami/rabbitmq:latest"
    container_name: 'rabbitmq'
    networks:
    - bankly-demo-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_PLUGINS=rabbitmq_management
    deploy:
      resources:
          limits:
              memory: 450M

networks:
    bankly-demo-network: