version: "3.9"
services:
  rabbit-mq:
    image: "bitnami/rabbitmq:latest"
    networks:
    - bankly-demo-network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_PLUGINS=rabbitmq_management
      - RABBITMQ_VHOST=bankly-demo-app
    deploy:
      resources:
          limits:
              memory: 200M
  
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
            memory: 500M

networks:
    bankly-demo-network: